In [5]:
import numpy as np

In [6]:
# Create an numpy array
arr1 = np.array([1, 2, 3, 4, 5, 6])
# printing the type of an array
print(type(arr1))
# printing the shape - dimension of an array
print("The shape of the array :", arr1.shape)

<class 'numpy.ndarray'>
The shape of the array : (6,)


In [ ]:
# convert 1 dim array to 2 dim arrau (2,3) as total we have 6 element
# 2 rows and let numpy decide how many column it should have to make total 6 element as we have 6 element in total
arr1 = arr1.reshape(2, -1)
print("Array after reshape:", arr1)
print("The 2-dmin shape of arr1 is ", arr1.shape)

Array after reshape: [[1 2 3]
 [4 5 6]]
The 2-dmin shape of arr1 is  (2, 3)


In [ ]:
# Creating numpy array based on some range and step
start = 0
end = 10
step = 1
range_arr = np.arange(start, end, step)
print("Array with arange method :", range_arr)

Array with arange method : [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Creating matirx of all 1 and all 0
all_ones = np.ones([2, 3])
all_zeros = np.zeros([2, 3])
print("Array with all ones \n", all_ones)
print("Array with all zeros\n", all_zeros)
# Creating identity matrix (i.e diagonal value will be 1)
arr_identity = np.eye(3)
print("Idenity matrix \n ", arr_identity)

Array with all ones 
 [[1. 1. 1.]
 [1. 1. 1.]]
Array with all zeros
 [[0. 0. 0.]
 [0. 0. 0.]]
Idenity matrix 
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Some Comon Attributes of Numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("❓array :\n👉🏻", arr)
print("❓Shape of an array is :\n👉🏻", arr.shape)
print("❓The dimenison is : \n👉🏻", arr.ndim)
print("❓Total numbr of element in an numpy array :\n👉🏻", arr.size)  # (2*3)=6
print("❓Data type of numpy array :\n 👉🏻", arr.dtype)

❓array :
👉🏻 [[1 2 3]
 [4 5 6]]
❓Shape of an array is :
👉🏻 (2, 3)
❓The dimenison is : 
👉🏻 2
❓Total numbr of element in an numpy array :
👉🏻 6
❓Data type of numpy array :
 👉🏻 int64


### Some Vectorized Operations

In [ ]:
v1 = np.array([1, 2, 3, 4, 4])
v2 = np.array([4, 5, 3, 1, 2])
print("Addition of two vector v1 + v2 : \n", v1 + v2)
print("Subtraction of two vector v1 - v2 : \n", v1 - v2)
print("Multiplication of two vector v1 * v2 : \n", v1 * v2)
print("Division of two vector v1 / v2 : \n", v1 / v2)
# dot product of 2 vec which will result in scalar
print("Dot Product of v1@v2 is :", np.dot(v1, v2))
print("Dot Product of v1@v2 is :", v1 @ v2)

Addition of two vector v1 + v2 : 
 [5 7 6 5 6]
Subtraction of two vector v1 - v2 : 
 [-3 -3  0  3  2]
Multiplication of two vector v1 * v2 : 
 [ 4 10  9  4  8]
Division of two vector v1 / v2 : 
 [0.25 0.4  1.   4.   2.  ]
Dot Product of v1@v2 is : 35
Dot Product of v1@v2 is : 35


In [ ]:
# Indexing and Slicing Operation in an numpy array
arr = np.array(
    [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
)
print("Shape of an array is ", arr.shape)
# Extracting 7,8,9,12,13,14
arr[1:-1, 1:-1]

Shape of an array is  (4, 5)


array([[ 7,  8,  9],
       [12, 13, 14]])

#### Statistical Concepts - Standardization & Normalization

In [50]:
# Normaization = It is a statistical concept to convert the data point to range of scale between [0,1]
# Standardization = It is a statistical concept where mean = 0 and standard-deviation = 1
def normalization(X):
    # finding min and max value
    x_min = np.min(X)
    x_max = np.max(X)

    return (X - x_min) / (x_max - x_min)


vec1 = np.array([20, 12, 14, 44, 25, 16, 17, 88, 99, 23, 47])
normalized_vec = normalization(vec1)
print("Normalized value of vec1 : ", normalized_vec)

Normalized value of vec1 :  [0.09195402 0.         0.02298851 0.36781609 0.14942529 0.04597701
 0.05747126 0.87356322 1.         0.12643678 0.40229885]


In [ ]:
# Some descriptive statistics calcualtion
# mean, median, mode , standard-deviation
arr = np.array([2, 3, 4, 5, 67, 2])
print("Mean :", np.mean(arr))
print("Median :", np.median(arr))
val, counts = np.unique(arr, return_counts=True)
max_value_indx = np.argmax(counts)  # this will return the index which has maximum value
print("Mode :", val[max_value_indx])
print("Standard-deviation:", np.std(arr))

Mean : 13.833333333333334
Median : 3.5
Mode : 2
Standard-deviation: 23.800676927814937


In [ ]:
# Logical operation
arr1 = np.array([1, 2, 33, 2, 22, 6, 5, 33, 77, 21])
print("Return an array with true or false according to the condition", arr1 > 5)
# get all element that are > 5
print("print all elements that are greater then 5 :", arr1[arr1 > 5])

Return an array with true or false according to the condition [False False  True False  True  True False  True  True  True]
print all elements that are greater then 5 : [33 22  6 33 77 21]
